---
title: "scratchpad"
author: "Eric Hoffmeyer"
date: "2023-10-17"
#output: html_document
---


```{r}
?getBM
?listAttributes
```

```{r}
listAttributes(mart = dataset)
```

```{r}
temp2 <- getBM(attributes = c("external_gene_name", 
                                "transcript_biotype",
                                "peptide_version",
                                "strain_name",
                                "biogrid",
                                "hgnc_id",
                                "hpa_id"),
                 filters = c("chromosomal_region"),
                 values = temp, 
                 mart = dataset)
```
```{r}
"reactome",
"uniprot_gn_id",
"mirbase_id",
"protein_id"
```


```{r}
temp2 |> 
  filter(external_gene_name == "JAK2")
```


```{r}
temp3 <- getBM(attributes = c("external_gene_name", 
                              "uniprot_gn_id", 
                              "mirbase_id", 
                              "protein_id"),
                 filters = c("chromosomal_region"),
                 values = temp, 
                 mart = dataset)
```

```{r}
temp3 |> 
  filter(external_gene_name == "JAK2")
```




















